-- Create comprehensive visa services menu for GSI Bali Agency based on immigration PDF
UPDATE restaurants 
SET data = jsonb_set(
    data::jsonb,
    '{menu}',
    '[
        {
            "id": "gsi_visit_visa_b211a",
            "dish": "Visit Visa (B211A)",
            "name": "Visit Visa (B211A)", 
            "title": "Visit Visa (B211A)",
            "price": "$35",
            "description": "30-day tourist visa, extendable once for another 30 days. Perfect for short visits to Indonesia.",
            "category": "Tourist Visas",
            "subcategory": "Tourist Visas",
            "restaurant_category": "Tourist Visas",
            "restaurant_categories": ["Tourist Visas"],
            "ingredients": ["Passport", "Return ticket", "Proof of funds"],
            "allergens": [],
            "is_vegan": false,
            "is_vegetarian": false,
            "is_gluten_free": false,
            "is_dairy_free": false,
            "is_nut_free": true,
            "dietary_tags": []
        },
        {
            "id": "gsi_visit_visa_b211b",
            "dish": "Visit Visa (B211B)",
            "name": "Visit Visa (B211B)",
            "title": "Visit Visa (B211B)", 
            "price": "$50",
            "description": "60-day business/social visit visa. Ideal for business meetings, conferences, or visiting family.",
            "category": "Business Visas",
            "subcategory": "Business Visas",
            "restaurant_category": "Business Visas",
            "restaurant_categories": ["Business Visas"],
            "ingredients": ["Passport", "Invitation letter", "Business documents"],
            "allergens": [],
            "is_vegan": false,
            "is_vegetarian": false,
            "is_gluten_free": false,
            "is_dairy_free": false,
            "is_nut_free": true,
            "dietary_tags": []
        },
        {
            "id": "gsi_b213_kitas",
            "dish": "B213 KITAS (Stay Permit)",
            "name": "B213 KITAS (Stay Permit)",
            "title": "B213 KITAS (Stay Permit)",
            "price": "$500",
            "description": "1-year renewable stay permit for various purposes including investment, retirement, or family reunification.",
            "category": "Long-term Permits",
            "subcategory": "Long-term Permits",
            "restaurant_category": "Long-term Permits",
            "restaurant_categories": ["Long-term Permits"],
            "ingredients": ["Passport", "Sponsor letter", "Health certificate", "Police clearance"],
            "allergens": [],
            "is_vegan": false,
            "is_vegetarian": false,
            "is_gluten_free": false,
            "is_dairy_free": false,
            "is_nut_free": true,
            "dietary_tags": []
        },
        {
            "id": "gsi_investment_visa",
            "dish": "Investment Visa (VITAS)",
            "name": "Investment Visa (VITAS)",
            "title": "Investment Visa (VITAS)",
            "price": "$750",
            "description": "For foreign investors establishing business in Indonesia. Includes work authorization and multiple entry privileges.",
            "category": "Investment Visas",
            "subcategory": "Investment Visas",
            "restaurant_category": "Investment Visas",
            "restaurant_categories": ["Investment Visas"],
            "ingredients": ["Investment plan", "Company documents", "Financial statements", "Passport"],
            "allergens": [],
            "is_vegan": false,
            "is_vegetarian": false,
            "is_gluten_free": false,
            "is_dairy_free": false,
            "is_nut_free": true,
            "dietary_tags": []
        },
        {
            "id": "gsi_retirement_visa",
            "dish": "Retirement Visa (B211A Special)",
            "name": "Retirement Visa (B211A Special)",
            "title": "Retirement Visa (B211A Special)",
            "price": "$400",
            "description": "For retirees 55+ years old. Renewable annually with pension proof. Enjoy your golden years in Indonesia.",
            "category": "Retirement Visas",
            "subcategory": "Retirement Visas",
            "restaurant_category": "Retirement Visas",
            "restaurant_categories": ["Retirement Visas"],
            "ingredients": ["Pension certificate", "Age proof (55+)", "Health insurance", "Passport"],
            "allergens": [],
            "is_vegan": false,
            "is_vegetarian": false,
            "is_gluten_free": false,
            "is_dairy_free": false,
            "is_nut_free": true,
            "dietary_tags": []
        },
        {
            "id": "gsi_family_visa",
            "dish": "Family Reunification Visa",
            "name": "Family Reunification Visa",
            "title": "Family Reunification Visa",
            "price": "$300",
            "description": "For spouses and children of Indonesian citizens or KITAS holders. Includes dependent visa processing.",
            "category": "Family Visas",
            "subcategory": "Family Visas",
            "restaurant_category": "Family Visas",
            "restaurant_categories": ["Family Visas"],
            "ingredients": ["Marriage certificate", "Sponsor KITAS", "Birth certificates", "Passport"],
            "allergens": [],
            "is_vegan": false,
            "is_vegetarian": false,
            "is_gluten_free": false,
            "is_dairy_free": false,
            "is_nut_free": true,
            "dietary_tags": []
        },
        {
            "id": "gsi_work_permit",
            "dish": "Work Permit (IMTA)",
            "name": "Work Permit (IMTA)",
            "title": "Work Permit (IMTA)",
            "price": "$600",
            "description": "Foreign worker employment permit. Required for all foreign employees in Indonesia. Includes RPTKA processing.",
            "category": "Work Permits",
            "subcategory": "Work Permits",
            "restaurant_category": "Work Permits",
            "restaurant_categories": ["Work Permits"],
            "ingredients": ["Employment contract", "Company RPTKA", "Educational certificates", "Experience letters"],
            "allergens": [],
            "is_vegan": false,
            "is_vegetarian": false,
            "is_gluten_free": false,
            "is_dairy_free": false,
            "is_nut_free": true,
            "dietary_tags": []
        },
        {
            "id": "gsi_visa_consultation",
            "dish": "Visa Consultation",
            "name": "Visa Consultation",
            "title": "Visa Consultation",
            "price": "$100",
            "description": "Professional consultation to determine the best visa option for your situation. Includes document review and timeline.",
            "category": "Consultation Services",
            "subcategory": "Consultation Services",
            "restaurant_category": "Consultation Services",
            "restaurant_categories": ["Consultation Services"],
            "ingredients": ["Current documents", "Purpose statement", "Timeline requirements"],
            "allergens": [],
            "is_vegan": false,
            "is_vegetarian": false,
            "is_gluten_free": false,
            "is_dairy_free": false,
            "is_nut_free": true,
            "dietary_tags": []
        },
        {
            "id": "gsi_document_legalization",
            "dish": "Document Legalization",
            "name": "Document Legalization",
            "title": "Document Legalization",
            "price": "$150",
            "description": "Apostille and embassy legalization services for foreign documents. Required for visa applications.",
            "category": "Document Services",
            "subcategory": "Document Services",
            "restaurant_category": "Document Services",
            "restaurant_categories": ["Document Services"],
            "ingredients": ["Original documents", "Certified translations", "Notarization"],
            "allergens": [],
            "is_vegan": false,
            "is_vegetarian": false,
            "is_gluten_free": false,
            "is_dairy_free": false,
            "is_nut_free": true,
            "dietary_tags": []
        },
        {
            "id": "gsi_visa_extension",
            "dish": "Visa Extension Service",
            "name": "Visa Extension Service",
            "title": "Visa Extension Service",
            "price": "$200",
            "description": "Extend your current visa without leaving Indonesia. Available for most visa types with proper documentation.",
            "category": "Extension Services",
            "subcategory": "Extension Services",
            "restaurant_category": "Extension Services",
            "restaurant_categories": ["Extension Services"],
            "ingredients": ["Current visa", "Passport", "Extension fee", "Supporting documents"],
            "allergens": [],
            "is_vegan": false,
            "is_vegetarian": false,
            "is_gluten_free": false,
            "is_dairy_free": false,
            "is_nut_free": true,
            "dietary_tags": []
        }
    ]'::jsonb
)
WHERE restaurant_id = 'gsi_bali_agency';

-- Verify the menu was created
SELECT 
    restaurant_id,
    data->>'name' as name,
    jsonb_array_length(data->'menu') as menu_items_count,
    data->'menu'->0->>'title' as first_service,
    data->'menu'->1->>'title' as second_service
FROM restaurants 
WHERE restaurant_id = 'gsi_bali_agency';
