-- Setup Legal Business in Railway Database
-- Run this in Railway Query tab or via psql

-- 1. Create the legal business
INSERT INTO businesses (
    business_id, password, role, data, 
    business_type, metadata, rag_mode
) VALUES (
    'bali-legal-consulting',
    '$2b$12$LQv3c1yqBWVHxkd0LHAkCOYz6TtxMQJqhN8/LewKyNiGH9pyp2HJa', -- bcrypt hash of 'password123'
    'owner',
    '{"name": "Bali Business Consulting", "email": "info@balibusinessconsulting.com", "phone": "+62 812 3456 7890", "address": "Jl. Sunset Road No. 88, Seminyak, Bali", "website": "https://balibusinessconsulting.com", "description": "Your trusted partner for visa and legal services in Indonesia. 13+ years of experience."}'::jsonb,
    'legal_visa',
    '{"specialties": ["visa_services", "company_formation", "legal_consultation"], "years_experience": 13, "languages": ["English", "Indonesian", "Chinese"], "certifications": ["Licensed Legal Consultant", "Immigration Specialist", "Company Registration Expert"]}'::jsonb,
    'hybrid_smart'
) ON CONFLICT (business_id) DO NOTHING;

-- 2. Insert visa services
INSERT INTO products (id, business_id, name, description, price, category, product_type, duration, requirements, features, tags, available) VALUES
('bali-legal-consulting_remote_worker_kitas', 'bali-legal-consulting', 'Remote Worker KITAS', 'Digital Nomad/Remote Worker visa for Indonesia. Work legally from Bali and Indonesia for 1-2 years.', 1500, 'visa_services', 'service', '1-2 years', '{"documents": ["Passport (6+ months validity)", "Employment contract or freelance agreements", "Bank statements (3 months)", "Health insurance"], "eligibility": ["Remote employment or freelance work", "Minimum income $5000/month", "Clean criminal record"], "processing_time": "2-3 weeks"}'::jsonb, '["Legal remote work permit", "Multiple entry visa", "Tax benefits", "Can bring dependents", "Renewable", "Access to Indonesian banking"]'::jsonb, '["visa", "kitas", "remote work", "digital nomad", "work permit", "bali", "indonesia"]'::jsonb, true),

('bali-legal-consulting_retirement_kitas', 'bali-legal-consulting', 'Retirement KITAS', 'Retirement visa for those 55+ wanting to enjoy life in Indonesia. Valid for 1 year, renewable up to 5 years.', 1200, 'visa_services', 'service', '1 year renewable', '{"documents": ["Passport (18+ months validity)", "Pension statements", "Bank statements showing $1500+/month", "Health/life insurance", "CV/Resume"], "eligibility": ["Age 55 or older", "Proof of pension/retirement income", "Cannot work in Indonesia"], "processing_time": "2-3 weeks"}'::jsonb, '["1 year stay permit", "Renewable up to 5 years", "Multiple entry", "Can purchase property (leasehold)", "Bring spouse as dependent", "Open bank account"]'::jsonb, '["visa", "kitas", "retirement", "senior", "expat", "long stay", "indonesia"]'::jsonb, true),

('bali-legal-consulting_investor_kitas', 'bali-legal-consulting', 'Investor KITAS', 'For foreign investors and company directors. Includes work permit and stay permit.', 2000, 'visa_services', 'service', '2 years', '{"documents": ["Company documents (PT PMA)", "Director appointment letter", "Passport", "CV and certificates", "Company tax documents"], "eligibility": ["Director/Commissioner of PT PMA", "Minimum investment $1 million IDR", "Active company operations"], "processing_time": "3-4 weeks"}'::jsonb, '["Work and stay permit", "2 year validity", "Multiple entry", "Can be director", "Family KITAS available", "Path to KITAP (permanent stay)"]'::jsonb, '["visa", "kitas", "investor", "business", "work permit", "director", "pt pma"]'::jsonb, true),

('bali-legal-consulting_spouse_kitas', 'bali-legal-consulting', 'Spouse/Family KITAS', 'Dependent visa for spouses and children of KITAS holders.', 800, 'visa_services', 'service', 'Follows sponsor', '{"documents": ["Marriage certificate (legalized)", "Birth certificates for children", "Sponsor KITAS copy", "Passport", "Family photos"], "eligibility": ["Legal spouse of KITAS holder", "Children under 18", "Sponsor has valid KITAS"], "processing_time": "2 weeks"}'::jsonb, '["Same duration as sponsor", "Multiple entry", "Cannot work", "Study permitted", "Renewable with sponsor", "Family unity"]'::jsonb, '["visa", "kitas", "family", "spouse", "dependent", "children"]'::jsonb, true);

-- 3. Insert company formation services
INSERT INTO products (id, business_id, name, description, price, category, product_type, duration, requirements, features, tags, available) VALUES
('bali-legal-consulting_pt_pma_formation', 'bali-legal-consulting', 'PT PMA Company Formation', 'Foreign-owned company (PT PMA) formation. Complete setup including legal, tax, and permits.', 3500, 'company_services', 'service', '2-3 months', '{"documents": ["Passport copies of shareholders/directors", "Company name (3 options)", "Business plan", "Office lease agreement", "Capital evidence"], "requirements": ["Minimum 2 shareholders", "Minimum capital varies by business", "Local office address", "Indonesian tax number"], "process": ["Name approval", "Deed establishment", "Ministry approval", "Tax registration", "Business licenses"]}'::jsonb, '["100% foreign ownership", "Limited liability", "Can own property", "Hire foreign workers", "All business licenses", "Tax registration", "Bank account setup"]'::jsonb, '["company", "pt pma", "foreign investment", "business setup", "incorporation"]'::jsonb, true),

('bali-legal-consulting_cv_formation', 'bali-legal-consulting', 'CV (Local Company) Setup', 'Partnership company setup for mixed ownership. Lower capital requirements than PT PMA.', 1500, 'company_services', 'service', '3-4 weeks', '{"documents": ["ID copies of all partners", "Partnership agreement", "Office address proof", "Capital declaration"], "requirements": ["At least 2 partners", "Indonesian partner required", "Minimum capital IDR 50 million", "Local office"], "suitable_for": ["Small businesses", "Restaurants", "Shops", "Service businesses"]}'::jsonb, '["Quick setup", "Lower capital", "Local partnerships", "Operating licenses", "Tax registration", "Simpler reporting"]'::jsonb, '["company", "cv", "partnership", "local business", "small business"]'::jsonb, true),

('bali-legal-consulting_nib_oss', 'bali-legal-consulting', 'NIB & Business Licenses', 'Business registration number (NIB) and all required operational licenses via OSS system.', 500, 'company_services', 'service', '1-2 weeks', '{"documents": ["Company deed", "Director ID/passport", "Office documents", "Business description"], "includes": ["NIB registration", "Location permit", "Environmental permit", "Sector licenses"], "sectors": ["Tourism", "Trade", "Services", "Construction", "Manufacturing"]}'::jsonb, '["Online OSS registration", "All operational permits", "Sector specific licenses", "Import/export rights", "Regular compliance", "Annual reporting help"]'::jsonb, '["license", "nib", "oss", "permit", "business license", "operation"]'::jsonb, true);

-- 4. Insert property and legal services
INSERT INTO products (id, business_id, name, description, price, category, product_type, duration, requirements, features, tags, available) VALUES
('bali-legal-consulting_property_lease', 'bali-legal-consulting', 'Property Lease Agreement', 'Professional lease agreement drafting and registration for villas, land, or commercial property.', 300, 'property_legal', 'service', '2-3 days', '{"documents": ["Land certificates", "Owner ID", "Tenant details", "Property photos"], "includes": ["Agreement drafting", "Legal review", "Registration", "Tax advice"], "types": ["Villa lease", "Land lease", "Shop lease", "Office lease"]}'::jsonb, '["Legally binding", "Bilingual documents", "Notarized", "Extension clauses", "Dispute protection", "Clear terms"]'::jsonb, '["property", "lease", "rental", "agreement", "villa", "contract"]'::jsonb, true),

('bali-legal-consulting_nominee_agreement', 'bali-legal-consulting', 'Nominee Agreement Structure', 'Legal structure for property control through Indonesian nominee. Includes all protective agreements.', 800, 'property_legal', 'service', '1 week', '{"documents": ["Property details", "Nominee ID", "Buyer passport", "Funds evidence"], "agreements": ["Loan agreement", "Power of attorney", "Statement letter", "Lease agreement"], "protection": ["Full control rights", "Inheritance protection", "Sale rights"]}'::jsonb, '["Maximum protection", "Notarized documents", "Legal ownership structure", "Renewable", "Transferable", "Court enforceable"]'::jsonb, '["property", "nominee", "land", "ownership", "foreign buyer"]'::jsonb, true);

-- 5. Insert consultation services
INSERT INTO products (id, business_id, name, description, price, category, product_type, duration, requirements, features, tags, available) VALUES
('bali-legal-consulting_visa_consultation', 'bali-legal-consulting', 'Visa Consultation', 'One-on-one consultation about visa options, requirements, and best path for your situation.', 100, 'consultation_services', 'service', '1 hour', '{"preparation": ["Current visa status", "Purpose in Indonesia", "Financial situation", "Family status"], "topics": ["Visa types", "Requirements", "Costs", "Timeline", "Success probability"]}'::jsonb, '["Expert advice", "All visa options", "Requirement checklist", "Cost breakdown", "Timeline planning", "Q&A session"]'::jsonb, '["consultation", "visa", "advice", "planning", "immigration"]'::jsonb, true),

('bali-legal-consulting_business_consultation', 'bali-legal-consulting', 'Business Setup Consultation', 'Comprehensive consultation for starting a business in Indonesia. Legal structure, licenses, and taxes.', 150, 'consultation_services', 'service', '1.5 hours', '{"topics": ["Business structures", "Foreign ownership", "Capital requirements", "Licenses needed", "Tax implications"], "deliverables": ["Best structure advice", "Cost estimates", "Timeline", "Requirements list"]}'::jsonb, '["Legal structures", "Investment rules", "License requirements", "Tax planning", "Location advice", "Partner matching"]'::jsonb, '["consultation", "business", "company", "startup", "investment"]'::jsonb, true),

('bali-legal-consulting_legal_review', 'bali-legal-consulting', 'Contract/Document Review', 'Professional legal review of contracts, agreements, or official documents. Includes recommendations.', 200, 'consultation_services', 'service', '2-3 days', '{"documents": ["Contract/agreement to review", "Related documents", "Specific concerns"], "covers": ["Legal validity", "Risk assessment", "Terms analysis", "Recommendations"], "types": ["Employment contracts", "Business agreements", "Property documents", "Investment agreements"]}'::jsonb, '["Thorough review", "Risk identification", "Clause by clause analysis", "Negotiation points", "Legal compliance", "Written report"]'::jsonb, '["legal review", "contract", "agreement", "document", "analysis"]'::jsonb, true);

-- Check results
SELECT 'Legal business setup complete!' as status;
SELECT COUNT(*) as product_count FROM products WHERE business_id = 'bali-legal-consulting';